### ISSUE TITLE
There was a problem running the model.

### ISSUE THREAD

**Issue by DeBruyxuan** [Zy-Fang1102/E-Stega#17]
module.js:557
    throw err;
    ^

Error: Cannot find module 'GPT2'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v9.4.0 --silent` to unset it.

**Comment by Zy-Fang1102** [comment]
This issue is likely caused by an incompatibility between the npm `prefix` setting and `nvm`. Here’s how to fix it:

1. Delete the npm `prefix` configuration:
   ```bash
   npm config delete prefix
   ```

2. Switch to the correct Node.js version using `nvm`:
   ```bash
   nvm use --delete-prefix v9.4.0 --silent
   ```

3. Clear the npm cache and reinstall dependencies:
   ```bash
   npm cache clean --force
   npm install
   ```

4. If the `GPT2` module is missing, install it manually:
   ```bash
   npm install GPT2
   ```

5. (Optional) Upgrade to the latest LTS version of Node.js for better compatibility:
   ```bash
   nvm install --lts
   nvm use --lts
   ```

This should resolve your issue!
